# Generated by Django 5.0 on 2024-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
